package cn.edu.fudan.ss.xulvcai.fdubbs.api.restful.util.pool;

/**
 * The interface implemented by factories that generate resources to put in
 * the pool
 * @author hidennis
 * @param <T> The type of resource that this factory creates
 */
public interface ResourceFactory<T> {

	/**
     * Create a new resource 
     */
	public T createResource();
	
	/**
     * Validate an existing resource generated by this factory.  Reset
     * any parameters to the defaults, or return false if the resource cannot
     * be reset.
     */
	public boolean validateResource(T resource);
}
